weights: ''
cfg: ./models/airplane_binary_yolo5s.yaml
data: data/airplane_binary.yaml
hyp: data/hyp.scratch.yaml
epochs: 400
batch_size: 4
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: airplane_binary_yolo5s_results
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 4
world_size: 1
global_rank: -1
